---
- hosts: default
  user: vagrant
  sudo: True


  tasks:

    - name: install packages
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items:
        - socat
        - icecast2
        - liquidsoap
        - liquidsoap-plugin-all

    - action: shell whoami
      register: whoami

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: enable icecast
      lineinfile: dest=/etc/default/icecast2 regexp=^ENABLE= line=ENABLE=true

    - name: update icecast configuration
      action: copy src=icecast.xml dest=/etc/icecast2/icecast.xml
      notify:
        - restart icecast2

    - name: create liquidsoap channel
      action: copy src=video.liq dest=/etc/liquidsoap/video.liq
      notify:
        - restart liquidsoap

    - name: create shell script
      action: copy src=shelliq dest=/usr/bin/shelliq

  handlers:
    - name: restart icecast2
      service: name=icecast2 state=restarted

    - name: restart liquidsoap
      service: name=liquidsoap state=restarted
